behaviors:
  EnemyShip:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3
    
    reward_signals:
      extrinsic:
        gamma: 0.99  
        strength: 1.0
    
    time_horizon: 1024  
    max_steps: 10_000_000
    summary_freq: 10_000
 
environment_parameters:
  enemy_difficulty:
    curriculum:
      - name: BP_Freeze
        completion_criteria:
          measure: reward
          behavior: EnemyShip
          threshold: 0.8
          min_lesson_length: 100
          signal_smoothing: true
        value: 0

      - name: BP_Slow
        completion_criteria:
          measure: reward
          behavior: EnemyShip
          threshold: 1.3
          min_lesson_length: 200
          signal_smoothing: true
        value: 1

      - name: BP_Medium
        completion_criteria:
          measure: reward
          behavior: EnemyShip
          threshold: 1.6
          min_lesson_length: 200
          signal_smoothing: true
        value: 2

      - name: BP_Fast
        completion_criteria:
          measure: reward
          behavior: EnemyShip
          threshold: 1.9
          min_lesson_length: 300
          signal_smoothing: true
        value: 3

      - name: PI_Slow
        completion_criteria:
          measure: reward
          behavior: EnemyShip
          threshold: 2.2
          min_lesson_length: 300
          signal_smoothing: true
        value: 4

      - name: PI_Medium
        completion_criteria:
          measure: reward
          behavior: EnemyShip
          threshold: 2.5
          min_lesson_length: 300
          signal_smoothing: true
        value: 5

      - name: PI_Fast
        completion_criteria:
          measure: reward
          behavior: EnemyShip
          threshold: 2.8
          min_lesson_length: 400
          signal_smoothing: true
        value: 6

      - name: AT_Slow
        completion_criteria:
          measure: reward
          behavior: EnemyShip
          threshold: 3.0
          min_lesson_length: 400
          signal_smoothing: true
        value: 7

      - name: AT_Medium
        completion_criteria:
          measure: reward
          behavior: EnemyShip
          threshold: 3.3
          min_lesson_length: 400
          signal_smoothing: true
        value: 8

      - name: AT_Fast
        value: 9


